name: Build TWRP-14 recovery for froggerPro

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  recovery:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize Github Runner Space
        uses: justinthelaw/maximize-github-runner-space@v0.9.0
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync git build-essential bc bison flex libssl-dev libelf-dev python3 python3-pip curl zip unzip
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo cp ~/repo /usr/local/bin/
          rm ~/repo

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Set up TWRP-14 Build Environment
        id: setup-twrp
        run: |
          RAM=$(awk '/MemTotal/ { printf "%.0f", $2 / 1000 / 1024 }' /proc/meminfo)
          CORES=$(nproc)
          START_TIME=$(date +%s)
          echo "Syncing will take some time... like 20min.. this runner has $CORES vcores and has $RAM GB RAM"
          repo init --depth=1 -u https://github.com/nebrassy/platform_manifest_twrp_aosp.git -b twrp-14
          sed -i '\|<remove-project path="external/guava" />|d' .repo/manifests/remove-minimal.xml
          repo sync -j$(nproc)
          END_TIME=$(date +%s)

          echo "sync_time=$((END_TIME - START_TIME))" >> $GITHUB_OUTPUT

      - name: Checkout Device Tree
        uses: actions/checkout@v7
        with:
          path: 'device/nothing/froggerPro'

      - name: Make and mount swapfile
        run: |
          sudo fallocate -l 16G ~/build_swap
          sudo chmod 600 ~/build_swap
          sudo mkswap ~/build_swap
          sudo swapon ~/build_swap

      - name: Build TWRP Recovery
        id: build-recovery
        run: |
          echo "Building.. will take a loooooong loooong time..."
          export ALLOW_MISSING_DEPENDENCIES=true
         
          START_TIME=$(date +%s)
          source build/envsetup.sh
          lunch twrp_froggerPro-ap2a-eng

          m recoveryimage
          END_TIME=$(date +%s)
          echo "build_time=$((END_TIME - START_TIME))" >> $GITHUB_OUTPUT

      - name: Clean up Swap
        run: |
          sudo swapoff ~/build_swap
          sudo rm -rf ~/build_swap

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: recovery-img-${{ github.sha }}
          path: |
            out/target/product/froggerPro/recovery.img
          compression-level: 9
          archive: true

      - name: Create Tag
        working-directory: 'device/nothing/froggerPro'
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          git fetch --tags

          latest_tag=$(git tag --list 'v*' --sort=-version:refname | head -n 1)

          if [ -z "$latest_tag" ]; then
            next_tag="v1.0.0"
          else
            version="${latest_tag#v}"
            IFS='.' read -r major minor patch <<< "$version"
            next_tag="v${major}.${minor}.$((patch + 1))"
          fi

          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$REPO.git
          git tag -a "$next_tag" "$SHA" -m "Release $next_tag"
          git push origin "$next_tag"
          echo "next_tag=$next_tag" >> $GITHUB_OUTPUT

      - name: Create Changelog
        env:
          SYNC_TIME: ${{ steps.setup-twrp.outputs.sync_time }}
          BUILD_TIME: ${{ steps.build-recovery.outputs.build_time }}
        run: |
          echo "" > ${{ github.workspace }}/changelog.txt
          echo "## Automatic TWRP Recovery Build for FroggerPro -- Nothing Phone (4a) Pro" >> ${{ github.workspace }}/changelog.txt
          echo "" >> ${{ github.workspace }}/changelog.txt
          echo "**TWRP Version:** 14.0" >> ${{ github.workspace }}/changelog.txt
          echo "**Sync Time:** $((SYNC_TIME / 60))m$((SYNC_TIME % 60))s" >> ${{ github.workspace }}/changelog.txt
          echo "**Build Time:** $((BUILD_TIME / 60))m$((BUILD_TIME % 60))s" >> ${{ github.workspace }}/changelog.txt
          echo "" >> ${{ github.workspace }}/changelog.txt
          echo "You can see this workflow run here: [Run #$GITHUB_RUN_NUMBER]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" >> ${{ github.workspace }}/changelog.txt


      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: 'TWRP release'
          files: out/target/product/froggerPro/recovery.img
          tag_name: ${{ steps.tag.outputs.next_tag }}
          body_path: ${{ github.workspace }}/changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

